### ISSUE TITLE
Some things

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [grrlgeek/bak-to-bacpac#7]
I will happily add any code/feature you ask.

Having variables at the top of each script is harder to maintain - Can I create a single place for them? Would that be useful?

Could I make it so that there is a deploy script which loads and calls a number of functions to do it?

**Comment by grrlgeek** [comment]
I would love to have a single list of variables and reference them across scripts! I wasn't sure how to do that.

**Comment by SQLDBAWithABeard** [comment]
#10 has done this
